### ISSUE TITLE
Non Composer Installation

### ISSUE THREAD

**Issue by neildavey** [Reviewscouk/magento2-reviews#1]
I am not using composer to add extensions - do you have the full files I can download so I can upload to my site via FTP and run magento upgrade?
Or point me to the right directopn please
Thanks

**Comment by StyxOfDynamite** [comment]
Hi Neil,

Apologies for the long delay in responding to this query.

I'm a little confused as this repository you've raised this issue against contains the source files.... Was there something you felt was missing ?

**Comment by StyxOfDynamite** [comment]
Hi @neildavey - I'm closing this issue, if you have any further queries please repoen it.
