### ISSUE TITLE
Pull through average review rating for simple and  configurable products

### ISSUE THREAD

**Issue by bexdoggett** [Reviewscouk/magento2-reviews#13]
Hello,

This isn't an issue - more a feature request. Is it possible to pull through the products average review summary (similar to Magento's default reviews) under the product title on the product page (& on the category page ideally) using your module? Currently we're using the reviews.co.uk api to get this information, but having issues with configurable products, so if it was included in your module that would be great!

Thanks

**Comment by StyxOfDynamite** [comment]
Hi Becky,

This can be done using the standalone **Product Rating Snippet** widget, available in the Reviews Dashboard.
