### ISSUE TITLE
Verified Buyer text missing in Static Content Widget

### ISSUE THREAD

**Issue by bexdoggett** [Reviewscouk/magento2-reviews#14]
Could you add in the 'verified buyer: yes' text that is in the javascript widget into the static content widget? We've switched to the static content widget to improve SEO, but the 'verified buyer' text is crucial too:
<img width="273" alt="screenshot 2019-02-04 08 50 17" src="https://user-images.githubusercontent.com/2361060/52198273-3140aa80-285a-11e9-8a32-8c211f25cb16.png">

**Comment by StyxOfDynamite** [comment]
Hi as we've corresponded directly I'm going to close this issue.

For anyone else after this, the suggested approach is to add the Verified Buyer badge using a CSS :after pseduoclass.
