### ISSUE TITLE
Content Security Policy Error

### ISSUE THREAD

**Issue by Mathanagopal97** [Reviewscouk/magento2-reviews#19]
In Magento 2.3.5-p1 live website I am getting the CSP Error. I have used the latest release and still I get this error. Please try to fix this error. If you need any more details please feel free to ask.

![Screenshot20200828135557-1919x992](https://user-images.githubusercontent.com/29875835/91539210-983f1c00-e936-11ea-826d-78668c671e13.png)

**Comment by Ben-Bromley** [comment]
Hi @Mathanagopal97, I believe that your Content Security Policy is blocking our script from loading, which is then causing the subsequent ReferenceErrors. Please amend your policy to allow our `widget.reviews.io` domain, and this should work fine.

Feel free to contact support@reviews.io if you need any further assistance.
