### ISSUE TITLE
Feature request: Add GTIN to product catalogue feed

### ISSUE THREAD

**Issue by erfanimani** [Reviewscouk/magento2-reviews#22]
In Reviews.io the ability exists to add product feeds. Product GTINs are necessary to connect with services, but the Magento module does not allow GTIN to be outputted in the feed.

Suggestion: in https://github.com/Reviewscouk/magento2-reviews/blob/master/Controller/Index/Feed.php add a GTIN property.

- Add store config option to select the product attribute that represents the GTIN
- If this product attribute is selected, add GTIN property to the feed
- If product attribute is not selected (left blank), skip GTIN property

**Comment by erfanimani** [comment]
Alternatively, I'm looking at the feed generation, and it looks exactly like a Google Shopping Feed.

Could any external extension that generates a Google Shopping Feed be used as the feed for Reviews.io?

**Comment by Ben-Bromley** [comment]
@erfanimani GTINs were added to our plugin in version `0.0.43`

https://github.com/Reviewscouk/magento2-reviews/blob/master/Controller/Index/Feed.php#L95

Apologies for the delay in response here. Hope this helps 😁

**Comment by erfanimani** [comment]
Thanks @Ben-Bromley, much appreciated. This is helpful — even better would have been to make the attribute code configurable as described, because now the expectation is that the merchant already has an attribute that exactly matches `gtin` or `upc`, but this would work too :)

Thanks
