### ISSUE TITLE
Change rich snippet info for review's Author.

### ISSUE THREAD

**Issue by Tirakal** [Reviewscouk/magento2-reviews#27]
Hi there. 
I need to change rich snippet info for Author. I mean the google Rich results test shows that Author's type is not mentioned. Could You please say how to modify it?

**Comment by dylannykolyszyn** [comment]
Hi Tirakal, apologies for the delay in answering this. This issue was fixed around a month ago following Google changing their Schema format expectations. If you're still seeing this error I'd recommend revalidating your products.
