### ISSUE TITLE
Exception #0 (Exception): Notice: Trying to access array offset on value of type null in /vendor/reviewscouk/reviews/Block/Richsnippet.php on line 51

### ISSUE THREAD

**Issue by steven-hardy** [Reviewscouk/magento2-reviews#28]
Hello,

I have this error when accessing the checkout - `Exception #0 (Exception): Notice: Trying to access array offset on value of type null in /Users/steven/Sites/suregreen/vendor/reviewscouk/reviews/Block/Richsnippet.php on line 51`

The line in question is below:

`'availability'  => $this->availability($current_product->getData('quantity_and_stock_status')['is_in_stock']),`

We are using a onestepcheckout from Mageplaza - `mageplaza/magento-2-one-step-checkout-extension`

The version of the extension is "0.0.40".

Is this a conflict between your extension and the mageplaza one? 

I have come across this issue when upgrading to magento 2.4.3.

Thank you for your help.

**Comment by wecreatedigital** [comment]
Has there been any progress on this?
